# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'train_set_param.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import QDialog, QFileDialog, QMessageBox

from libs.constants import DEFAULT_BATCH_SIZE, DEFAULT_EPOCHS
from libs.labelFile import LabelFile
from libs.ustr import ustr

__appname__ = 'LabelImg'
class Ui_trainSetParam(object):
    def setupUi(self, trainSetParam):
        trainSetParam.setObjectName("trainSetParam")
        trainSetParam.resize(606, 210)
        self.verticalLayout = QtWidgets.QVBoxLayout(trainSetParam)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainWidget = QtWidgets.QWidget(trainSetParam)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.paramHBox = QtWidgets.QHBoxLayout()
        self.paramHBox.setContentsMargins(-1, -1, 12, -1)
        self.paramHBox.setObjectName("paramHBox")
        self.batchSizeLabel = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.batchSizeLabel.setFont(font)
        self.batchSizeLabel.setObjectName("batchSizeLabel")
        self.paramHBox.addWidget(self.batchSizeLabel)
        self.batchSizeLine = QtWidgets.QLineEdit(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchSizeLine.sizePolicy().hasHeightForWidth())
        self.batchSizeLine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.batchSizeLine.setFont(font)
        self.batchSizeLine.setObjectName("batchSizeLine")
        self.paramHBox.addWidget(self.batchSizeLine)
        self.epochsLabel = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.epochsLabel.setFont(font)
        self.epochsLabel.setObjectName("epochsLabel")
        self.paramHBox.addWidget(self.epochsLabel)
        self.epochsLine = QtWidgets.QLineEdit(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epochsLine.sizePolicy().hasHeightForWidth())
        self.epochsLine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.epochsLine.setFont(font)
        self.epochsLine.setObjectName("epochsLine")
        self.paramHBox.addWidget(self.epochsLine)
        self.verticalLayout_2.addLayout(self.paramHBox)
        self.yamlPathHBox = QtWidgets.QHBoxLayout()
        self.yamlPathHBox.setObjectName("yamlPathHBox")
        self.yamlPathLabel = QtWidgets.QLabel(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yamlPathLabel.setFont(font)
        self.yamlPathLabel.setObjectName("yamlPathLabel")
        self.yamlPathHBox.addWidget(self.yamlPathLabel)
        self.yamlPathLine = QtWidgets.QLineEdit(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yamlPathLine.sizePolicy().hasHeightForWidth())
        self.yamlPathLine.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yamlPathLine.setFont(font)
        self.yamlPathLine.setReadOnly(True)
        self.yamlPathLine.setObjectName("yamlPathLine")
        self.yamlPathHBox.addWidget(self.yamlPathLine)
        self.yamlPathButton = QtWidgets.QPushButton(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.yamlPathButton.setFont(font)
        self.yamlPathButton.setObjectName("yamlPathButton")
        self.yamlPathHBox.addWidget(self.yamlPathButton)
        self.verticalLayout_2.addLayout(self.yamlPathHBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.mainWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.mainWidget)

        self.retranslateUi(trainSetParam)
        self.buttonBox.accepted.connect(trainSetParam.accept)  # type: ignore
        self.buttonBox.rejected.connect(trainSetParam.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(trainSetParam)

    def retranslateUi(self, trainSetParam):
        _translate = QtCore.QCoreApplication.translate
        trainSetParam.setWindowTitle(_translate("trainSetParam", "设置训练参数"))
        self.batchSizeLabel.setText(_translate("trainSetParam", "训练规模："))
        self.epochsLabel.setText(_translate("trainSetParam", "迭代次数："))
        self.yamlPathLabel.setText(_translate("trainSetParam", "YAML路径："))
        self.yamlPathButton.setText(_translate("trainSetParam", "选择"))


class TrainSetParam(QDialog, Ui_trainSetParam):
    def __init__(self, parent=None):
        super(TrainSetParam, self).__init__()
        self.setupUi(self)
        self.parent = parent
        self.batchSizeLine.setText(str(DEFAULT_BATCH_SIZE))
        self.epochsLine.setText(str(DEFAULT_EPOCHS))
        self.yamlPathButton.clicked.connect(lambda: self.set_yaml_path())
        self.buttonBox.accepted.connect(lambda: self.buttonBox_accepted())
        self.batchSizeLine.setValidator(QIntValidator())
        self.epochsLine.setValidator(QIntValidator())

    def set_yaml_path(self):
        path = os.path.dirname(ustr(self.parent.file_path)) if self.parent.file_path else '.'
        formats = ['*.yaml']
        filters = "Data Files (yaml Only %s)" % ' '.join(formats + ['*%s' % LabelFile.suffix])
        filename, _ = QFileDialog.getOpenFileName(self, '%s - Choose model file' % __appname__, path, filters)
        if filename:
            if isinstance(filename, (tuple, list)):
                filename = filename[0]
        else:
            return
        yaml_file_path = filename
        self.yamlPathLine.setText(yaml_file_path)

    def buttonBox_accepted(self):
        self.close()


